### ISSUE TITLE
not working with fb flipper

### ISSUE THREAD

**Issue by vonovak** [wultra/react-native-powerauth-mobile-sdk#29]
Hello, 
I'd like to report that ~~since v1.5.1~~ I'm getting an error when running `pod install` in a RN project that uses flipper.

edit: the issue is present even prior to 1.5.1 because back then, autolinking did not work. `react-native-powerauth-mobile-sdk@1.4.11` seems to work okay, but it's outdated.

```
[!] The 'Pods-abc' target has frameworks with conflicting names: openssl.xcframework.
```

I believe you ran into the same error yourself in the demo project in this repo, and the problem was worked around by simply commenting out the flipper installation from the podfile: 

https://github.com/wultra/react-native-powerauth-mobile-sdk/commit/37dd35e61cc5a3d99c7263c220db4064ca32721d#diff-2a41dcb8718e9aa767e8163fcc6f4c8d71c923c3681a467118214f288f5691ee

However, flipper is a critical tool for debugging react native apps and "commenting out" is not a solution. It would be appreciated if this was fixed. Thank you! :)

**Comment by kober32** [comment]
Hi, thanks for reporting.

Yes, sadly, I know...

I already discussed this with our native SDK developer a few weeks ago and we will be removing the `opnssl.xcframework` in favor of `PowerAuthCore.xcframework` that will be replacing it.

I created an [issue for it](https://github.com/wultra/powerauth-mobile-sdk/issues/371) so I can keep an eye on it, but there is no ETA right now.

I'll keep you updated once this will be resolved.

**Comment by kober32** [comment]
Resolved in v `2.1.0`

**Comment by vixentael** [comment]
Hi everyone!

I am one of [Themis](https://github.com/cossacklabs/themis) maintainers. We also use openssl under the hood (we even support [a separate OpenSSL package for SPM](https://github.com/cossacklabs/openssl-apple)), and we run into similar issue with flipper.

> Resolves Get rid of openssl.xcframework in iOS SDK #371 because openssl will be already linked in PowerAuthCore

Could you please elaborate more developer-to-developer, how exactly do you link openssl now? As a static library inside PowerAuthCore?

cc @radetsky

**Comment by kober32** [comment]
Hi @vixentael, 

AFAIK - yes, it's a static library inside our `PowerAuthCore.xcframework`, but @hvge  (as the native maintainer) can elaborate much better.

**Comment by petrdvorak** [comment]
@vixentael Technically, we fixed this in the issue wultra/powerauth-mobile-sdk#373 in the native library, among many other things, essentially by linking the openssl into a separate dynamic framework. Again, @hvge is welcome here with more comments, I just wanted to say "hi!" 😆...

**Comment by vixentael** [comment]
Hiiiiiiii 🤗🤗🤗!

Thank you @kober32 and @petrdvorak :)

We will check your code in more details searching for inspiration :))

Previously, we already had a story of building Themis for Carthage and selecting the best way to link OpenSSL. That journey was full of WTFs and resulted in [a nice blogpost](https://www.cossacklabs.com/blog/openssl-for-carthage-for-themis.html) 😅

Apparently, we will need to dig into static-dynamic linking again. 

_I love mobile platforms 😣_

**Comment by hvge** [comment]
Hi @vixentael 
guys above are right, we just wrapped OpenSSL into our `PowerAuthCore` module, which is now dynamic framework. The trick for CocoaPods was to do not expose OpenSSL as a provided framework. We maintain our own OpenSSL build for our own purposes (stripped from unused ciphers, etc..), distributed as a precompiled static libraries for all platforms and supported architectures.

The hierarchy of libs looks like this (from bottom to top):

- `openssl.xcframework` - provided by [wultra/cc7/openssl-build](https://github.com/wultra/cc7/tree/develop/openssl-build)
  - The binary, precompiled artifacts are available for download from a release page as a release asset. For example, see Assets at [0.3.5](https://github.com/wultra/cc7/releases/tag/0.3.5).
  - The static xcframework contains only `libcrypto` part of OpenSSL

- `cc7` is a simple static C++ library providing primitives, like auto-cleanup arrays for Android & iOS platforms
  - The Xcode project has a script step that downloads precompiled `openssl` before the build.
   
- `PowerAuthLib` is static C++ library providing core functionality for our PowerAuth protocol on mobile platforms.
  - Depends on `openssl` and `cc7`

- `PowerAuthCore` is now dynamic framework, linking `PowerAuthLib`, `cc7` and `openssl` (libcrypto) into one final module.
  - Check xcode project at https://github.com/wultra/powerauth-mobile-sdk/tree/develop/proj-xcode for more details.

- `PowerAuth2` is high level SDK, provided as a dynamic framework.
  - Depends on `PowerAuthCore` module only.
 

On iOS, we maintain all the dependencies with using git submodules and with the nested Xcode projects. So, you can simply open `PowerAuth2.xcodeproj` and you'll see the whole hierarchy of libs.

Btw we met personally a couple of years ago at Avast HQ. You were presenting some topics about mobile development I think 😀

**Comment by vixentael** [comment]
@hvge thank you a lot for this detailed explanation! it helps us a lot! i remember that meetup at Avast HQ :)

@radetsky wrote a Themis React Native wrapper and now we are trying to make a workable RN package which includes all the fun with openssl :))
