### ISSUE TITLE
Include “original exceptions” that are referenced in some exceptions

### ISSUE THREAD

**Issue by kober32** [wultra/react-native-powerauth-mobile-sdk#35]

**Comment by kober32** [comment]
This is meant for `PowerAuthErrorException`.

A real-world example from a client:

1. Tries to call `addBiometryFactor`
2. On the native layer, `PowerAuthErrorException` is caught with code `NETWORK_ERROR`
3. The error is reported to the JS layer as such (`NETWORK_ERROR`)

The problem is, that in this case, a `FailedApiException` caused this and is accessible via the `getCause()` method, but this information (endpoint that was called and what was the actual networking error), is lost as it's not propagated to the JS layer.

**Comment by hvge** [comment]
OK, this particular case was improved in #55 / #58. The developer no longer needs to dig deeper into exceptions to determine the exact reason of the failure. I'll keep it open for possible improvements, but IMHO, from the functionality point of view, it's enough for developers to have `NETWORK_ERROR`, `RESPONSE_ERROR` and `AUTHENTICATION_ERROR`.

**Comment by kober32** [comment]
☝🏻  I agree, this was a result of a direct question by the client (who was complaining that he doesn't see the response during the development) and cannot determine, what is wrong.

Maybe there could be a debug option to print all exceptions thrown (including the nested one), to the JS console / native log for easier debugging.

**Comment by hvge** [comment]
I don't have any idea how to more improve this. There's already new possibility to trace failed native calls (see #116) so I close this ticket now.
