### ISSUE TITLE
Better handling of http errors 

### ISSUE THREAD

**Issue by kober32** [wultra/react-native-powerauth-mobile-sdk#51]
Right now, we handle network errors on the PowerAuth layer (`NETWORK_ERROR`) but not the networking itself.

For android, handle `IOException` and other common exceptions that can be thrown during the HTTP communication.

On iOS, handle `NSURLErrorDomain` domain on HTTP errors with cherry-picked errors from https://github.com/apportable/Foundation/blob/master/System/CFNetwork/include/CFNetwork/CFNetworkErrors.h

**Comment by kober32** [comment]
Note that this issue will surface a lot as there are a lot of exceptions that can be thrown and are not handled by the layer right now as it's impossible to catch and translate everything to the JS layer

**Comment by hvge** [comment]
Fixed together with #55
